Log/Log/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('cuentas/', include('cuentas.urls', namespace="cuentas"))
]

Log/cuentas/urls.py
from django.urls import path
from . import views

app_name = "cuentas"
urlpatterns = [
    path('login/', views.login_usuario, name="login"),
    path('logout/', views.logout_usuario, name='logout'),
    path('registrar/', views.registrar_usuario, name="registrar")
]

Log/cuentas/models.py
from django.db import models

Log/cuentas/forms.py
from django import forms
from django.contrib.auth.models import User

class UserRegistrationForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput())
    email = forms.EmailField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.TextInput())
    confirm_password = forms.CharField(widget=forms.TextInput())

    def clean(self):
        cleaned_data = super(UserRegistrationForm, self).clean()
        p1 = cleaned_data.get('password')
        p2 = cleaned_data.get('confirm_password')
        
        if p1 and p2:
            if p1 != p2:
                raise ValidationError('No coincide con la contraseña anterior')

Log/Log/views.py
from django.shortcuts import render

def home(request):
	return render(request, 'home.html', {})

Log/cuentas/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, ReadOnlyPasswordHashField, AuthenticationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from . forms import UserRegistrationForm
# Create your views here.

def login_usuario(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        remeber = request.POST.get('remeber')
        if remeber:
            settings.SESSION_EXPIRE_AT_BROWSER_CLOSE = False
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect('/')
        else:
            messages.error(request, 'Bad username or password')
    return render(request, 'login.html', {})

def logout_usuario(request):
    logout(request)
    return redirect('cuentas:login')

def registrar_usuario(request):
    if request.method == "POST":
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user = User.objects.create_user(username, email=email, password=password)
            messages.success(request, 'Gracias por registrarse {}'.format(user.username))
            return redirect('cuentas:login')
    else:
        form = UserRegistrationForm()
    return render(request, 'registrar.html', {'form':form})

Log/cuentas/templates/login.html
{% extends 'base.html' %}
{% block title %}Login{% endblock %}
{% load static %}
{% block custom_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col s12 m8 offset-m2 l8 offset-l2">
                <div class="card">
                    <form method="POST" action="">{% csrf_token %}
                        <div class="card-content">
                            <span class="card-title grey-text text-darken-2">Inicia sesión</span>
                            <div class="row">
                                <div class="input-field col s12">
                                    <i class="material-icons prefix">person</i>
                                    <input id="username" type="text" class="validate" name="username">
                                    <label for="username">Usuario</label>
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-field col s12">
                                    <i class="material-icons prefix">enhanced_encryption</i>
                                    <input id="password" type="password" class="validate" name="password">
                                    <label for="password">Password</label>
                                </div>
                            </div>
                            <div class="row">
                                <div class="checkbox-field col s12 right-align">
                                    <label>
                                        <input type="checkbox" class="filled-in" id="remember" name="remember">
                                        <span for="remember-me">Recordarme</span>
                                    </label>        
                                </div>
                            </div>
                        </div>
                        <div class="card-action">
                            <div class="right-align">
                                <a href="{% url 'cuentas:registrar' %}">Registrar</a>
                                <button class="btn waves-effect waves-light blue-grey darken-3" type="submit">Iniciar sesion</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Log/cuentas/templates/registrar.html
{% extends 'base.html' %}
{% block title %}Registrar{% endblock %}
{% load static %}
{% block custom_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col s12 m8 offset-m2 l8 offset-l2">
                <div class="card">
                    <form method="POST" action="">{% csrf_token %}
                        <div class="card-content">
                            <span class="card-title grey-text text-darken-2">Registrar</span>
                            <div class="row">
                                <div class="input-field col s12">
                                    <i class="material-icons prefix">person</i>
                                    <input id="username" type="text" class="validate" name="username">
                                    <label for="username">Usuario</label>
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-field col s12">
                                    <i class="material-icons prefix">email</i>
                                    <input id="email" type="text" class="validate" name="email">
                                    <label for="email">Correo</label>
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-field col s12">
                                    <i class="material-icons prefix">enhanced_encryption</i>
                                    <input id="password" type="password" class="validate" name="password">
                                    <label for="password">Password</label>
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-field col s12">
                                    <i class="material-icons prefix">enhanced_encryption</i>
                                    <input id="confirm_password" type="password" class="validate" name="confirm_password">
                                    <label for="confirm_password">Confirmar Password</label>
                                </div>
                            </div>
                        <div class="card-action">
                            <div class="right-align">
                                <button class="btn waves-effect waves-light blue-grey darken-3" type="submit">Registrar</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% block scripts %}
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            var elems = document.querySelectorAll('select');
            var options = document.querySelectorAll('option');
            var instances = M.FormSelect.init(elems, options);
        });
    </script>
{% endblock %}

{% endblock %}

Log/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    {% block custom_css%}{% endblock %}
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.min.css' %}"  media="screen,projection"/>

    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    
</head>
<body>
    {% block content %}
    {% endblock %}
    <!--JavaScript at end of body for optimized loading-->
    <script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>
{% block scripts %}
{% endblock %}
</body>
</html>

Log/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Home{% endblock %}
{% block custom_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
{% endblock %}

{% block content %}
    <h1>Bienvenido</h1>
    {% if user.is_authenticated %}
        <p>Hi {{ user.username }}!</p>
        <a href="{% url 'cuentas:logout' %}">Cerrar sesion</a>
    {% else %}
        <p>No estas logueado</p>
        <a href="{% url 'cuentas:login' %}">Inicia sesion</a>
    {% endif %}
{% endblock %}